// This file is auto-generated by scripts/generate-tests.ts. Do not edit by hand.
import { describe, it, expect } from 'vitest';
import { dispatch } from '../src/index';
import { commands, type CommandDescriptor } from '../src/commands.gen';

function cmd(resourceKey: string, methodName: string): CommandDescriptor {
  const found = commands.find((c) => c.resourceKey === resourceKey && c.methodName === methodName);
  if (!found) throw new Error(`No descriptor for ${resourceKey}.${methodName}`);
  return found;
}

function mockFetch() {
  const calls: { method: string; path: string }[] = [];
  const fetchImpl: typeof fetch = async (input, init) => {
    const url = new URL(String(input));
    calls.push({ method: init?.method ?? 'GET', path: url.pathname.replace(/^\/v1/, '') });
    return new Response(JSON.stringify({ success: true, data: {} }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  };
  return { fetchImpl, calls };
}

describe('account', () => {
  it('smartlyq account get-me -> GET /me', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('account', 'getMe'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/me');
  });

  it('smartlyq account get-me-usage -> GET /me/usage', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('account', 'getMeUsage'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/me/usage');
  });

  it('smartlyq account get-me-balance -> GET /me/balance', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('account', 'getMeBalance'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/me/balance');
  });
});

describe('captain', () => {
  it('smartlyq captain send-message -> POST /captain/messages', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('captain', 'sendMessage'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/captain/messages');
  });

  it('smartlyq captain list-conversations -> GET /captain/conversations', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('captain', 'listConversations'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/captain/conversations');
  });

  it('smartlyq captain get-conversation -> GET /captain/conversations/{conversation_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('captain', 'getConversation'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/captain/conversations/test-id');
  });
});

describe('analytics', () => {
  it('smartlyq analytics get-overview -> GET /analytics/overview', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('analytics', 'getOverview'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/overview');
  });

  it('smartlyq analytics get-posts -> GET /analytics/posts', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('analytics', 'getPosts'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/posts');
  });

  it('smartlyq analytics get-account -> GET /analytics/accounts/{account_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('analytics', 'getAccount'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/analytics/accounts/test-id');
  });
});

describe('articles', () => {
  it('smartlyq articles generate -> POST /articles/generate', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('articles', 'generate'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/articles/generate');
  });

  it('smartlyq articles list -> GET /articles', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('articles', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/articles');
  });

  it('smartlyq articles get -> GET /articles/{article_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('articles', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/articles/test-id');
  });

  it('smartlyq articles delete -> DELETE /articles/{article_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('articles', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/articles/test-id');
  });
});

describe('audio', () => {
  it('smartlyq audio text-to-speech -> POST /audio/text-to-speech', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('audio', 'textToSpeech'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/audio/text-to-speech');
  });

  it('smartlyq audio speech-to-text -> POST /audio/speech-to-text', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('audio', 'speechToText'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/audio/speech-to-text');
  });

  it('smartlyq audio get -> GET /audio/{audio_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('audio', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/audio/test-id');
  });
});

describe('chatbots', () => {
  it('smartlyq chatbots list -> GET /chatbots', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots');
  });

  it('smartlyq chatbots create -> POST /chatbots', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'create'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/chatbots');
  });

  it('smartlyq chatbots get -> GET /chatbots/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots/test-id');
  });

  it('smartlyq chatbots update -> PATCH /chatbots/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'update'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/chatbots/test-id');
  });

  it('smartlyq chatbots delete -> DELETE /chatbots/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/chatbots/test-id');
  });

  it('smartlyq chatbots train -> POST /chatbots/{id}/train', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'train'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/chatbots/test-id/train');
  });

  it('smartlyq chatbots get-train-status -> GET /chatbots/{id}/train-status', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'getTrainStatus'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots/test-id/train-status');
  });

  it('smartlyq chatbots send-message -> POST /chatbots/{id}/messages', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'sendMessage'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/chatbots/test-id/messages');
  });

  it('smartlyq chatbots list-conversations -> GET /chatbots/{id}/conversations', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'listConversations'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots/test-id/conversations');
  });

  it('smartlyq chatbots get-conversation-messages -> GET /chatbots/{id}/conversations/{conv_id}/messages', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('chatbots', 'getConversationMessages'), ['test-id', 'test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/chatbots/test-id/conversations/test-id/messages');
  });
});

describe('comments', () => {
  it('smartlyq comments list -> GET /social/comments', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('comments', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/comments');
  });

  it('smartlyq comments reply-to -> POST /social/comments/{comment_id}/reply', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('comments', 'replyTo'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/comments/test-id/reply');
  });

  it('smartlyq comments hide -> POST /social/comments/{comment_id}/hide', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('comments', 'hide'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/comments/test-id/hide');
  });

  it('smartlyq comments delete -> DELETE /social/comments/{comment_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('comments', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/comments/test-id');
  });
});

describe('content', () => {
  it('smartlyq content rewrite -> POST /content/rewrite', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('content', 'rewrite'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/content/rewrite');
  });

  it('smartlyq content generate-caption -> POST /content/caption', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('content', 'generateCaption'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/content/caption');
  });
});

describe('contacts', () => {
  it('smartlyq contacts list -> GET /contacts', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/contacts');
  });

  it('smartlyq contacts create -> POST /contacts', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'create'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts');
  });

  it('smartlyq contacts get -> GET /contacts/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/contacts/test-id');
  });

  it('smartlyq contacts update -> PATCH /contacts/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'update'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/contacts/test-id');
  });

  it('smartlyq contacts add-tags -> POST /contacts/{id}/tags', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'addTags'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts/test-id/tags');
  });

  it('smartlyq contacts remove-tags -> DELETE /contacts/{id}/tags', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'removeTags'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/contacts/test-id/tags');
  });

  it('smartlyq contacts list-notes -> GET /contacts/{id}/notes', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'listNotes'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/contacts/test-id/notes');
  });

  it('smartlyq contacts add-note -> POST /contacts/{id}/notes', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'addNote'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts/test-id/notes');
  });

  it('smartlyq contacts enroll -> POST /contacts/{id}/enroll', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'enroll'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts/test-id/enroll');
  });

  it('smartlyq contacts add-message -> POST /contacts/{id}/messages', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('contacts', 'addMessage'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/contacts/test-id/messages');
  });
});

describe('custom-fields', () => {
  it('smartlyq custom-fields list -> GET /custom-fields', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('customFields', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/custom-fields');
  });

  it('smartlyq custom-fields create -> POST /custom-fields', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('customFields', 'create'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/custom-fields');
  });

  it('smartlyq custom-fields delete -> DELETE /custom-fields/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('customFields', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/custom-fields/test-id');
  });
});

describe('opportunities', () => {
  it('smartlyq opportunities list-pipelines -> GET /pipelines', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('opportunities', 'listPipelines'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/pipelines');
  });

  it('smartlyq opportunities create-pipeline -> POST /pipelines', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('opportunities', 'createPipeline'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/pipelines');
  });

  it('smartlyq opportunities list -> GET /opportunities', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('opportunities', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/opportunities');
  });

  it('smartlyq opportunities create -> POST /opportunities', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('opportunities', 'create'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/opportunities');
  });

  it('smartlyq opportunities get -> GET /opportunities/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('opportunities', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/opportunities/test-id');
  });

  it('smartlyq opportunities update -> PATCH /opportunities/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('opportunities', 'update'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/opportunities/test-id');
  });

  it('smartlyq opportunities delete -> DELETE /opportunities/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('opportunities', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/opportunities/test-id');
  });

  it('smartlyq opportunities update-status -> POST /opportunities/{id}/status', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('opportunities', 'updateStatus'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/opportunities/test-id/status');
  });
});

describe('messages', () => {
  it('smartlyq messages list-conversations -> GET /social/conversations', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('messages', 'listConversations'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/conversations');
  });

  it('smartlyq messages list -> GET /social/conversations/{conversation_id}/messages', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('messages', 'list'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/conversations/test-id/messages');
  });

  it('smartlyq messages send -> POST /social/conversations/{conversation_id}/messages', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('messages', 'send'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/conversations/test-id/messages');
  });

  it('smartlyq messages mark-conversation-read -> POST /social/conversations/{conversation_id}/read', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('messages', 'markConversationRead'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/conversations/test-id/read');
  });
});

describe('images', () => {
  it('smartlyq images generate -> POST /images/generate', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('images', 'generate'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/images/generate');
  });

  it('smartlyq images list -> GET /images', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('images', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/images');
  });

  it('smartlyq images get -> GET /images/{image_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('images', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/images/test-id');
  });

  it('smartlyq images delete -> DELETE /images/{image_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('images', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/images/test-id');
  });
});

describe('jobs', () => {
  it('smartlyq jobs list -> GET /jobs', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('jobs', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/jobs');
  });

  it('smartlyq jobs get -> GET /jobs/{job_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('jobs', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/jobs/test-id');
  });

  it('smartlyq jobs cancel -> POST /jobs/{job_id}/cancel', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('jobs', 'cancel'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/jobs/test-id/cancel');
  });
});

describe('media', () => {
  it('smartlyq media list -> GET /media', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('media', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/media');
  });

  it('smartlyq media get -> GET /media/{media_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('media', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/media/test-id');
  });

  it('smartlyq media delete -> DELETE /media/{media_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('media', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/media/test-id');
  });

  it('smartlyq media get-upload-url -> POST /media/upload-url', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('media', 'getUploadUrl'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/media/upload-url');
  });
});

describe('presentations', () => {
  it('smartlyq presentations generate -> POST /presentations/generate', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('presentations', 'generate'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/presentations/generate');
  });

  it('smartlyq presentations list -> GET /presentations', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('presentations', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/presentations');
  });

  it('smartlyq presentations get -> GET /presentations/{presentation_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('presentations', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/presentations/test-id');
  });

  it('smartlyq presentations delete -> DELETE /presentations/{presentation_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('presentations', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/presentations/test-id');
  });
});

describe('profiles', () => {
  it('smartlyq profiles list -> GET /profiles', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/profiles');
  });

  it('smartlyq profiles create -> POST /profiles', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'create'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles');
  });

  it('smartlyq profiles get -> GET /profiles/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/profiles/test-id');
  });

  it('smartlyq profiles delete -> DELETE /profiles/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/profiles/test-id');
  });

  it('smartlyq profiles list-accounts -> GET /profiles/{id}/accounts', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'listAccounts'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/profiles/test-id/accounts');
  });

  it('smartlyq profiles pause -> POST /profiles/{id}/pause', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'pause'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles/test-id/pause');
  });

  it('smartlyq profiles resume -> POST /profiles/{id}/resume', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'resume'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles/test-id/resume');
  });

  it('smartlyq profiles create-connect-link -> POST /profiles/{id}/connect-link', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'createConnectLink'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles/test-id/connect-link');
  });

  it('smartlyq profiles create-connect-url -> POST /profiles/{id}/connect/{platform}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'createConnectUrl'), ['test-id', 'test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/profiles/test-id/connect/test-id');
  });

  it('smartlyq profiles get-account-billing -> GET /me/account-billing', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('profiles', 'getAccountBilling'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/me/account-billing');
  });
});

describe('seo', () => {
  it('smartlyq seo keyword-research -> POST /seo/keyword-research', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'keywordResearch'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/keyword-research');
  });

  it('smartlyq seo serp -> POST /seo/serp', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'serp'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/serp');
  });

  it('smartlyq seo keyword-difficulty -> POST /seo/keyword-difficulty', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'keywordDifficulty'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/keyword-difficulty');
  });

  it('smartlyq seo ranked-keywords -> POST /seo/ranked-keywords', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'rankedKeywords'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/ranked-keywords');
  });

  it('smartlyq seo domain-overview -> POST /seo/domain-overview', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'domainOverview'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/domain-overview');
  });

  it('smartlyq seo competitors -> POST /seo/competitors', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'competitors'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/competitors');
  });

  it('smartlyq seo backlinks-summary -> POST /seo/backlinks-summary', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'backlinksSummary'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/backlinks-summary');
  });

  it('smartlyq seo audit -> POST /seo/audit', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'audit'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/audit');
  });

  it('smartlyq seo backlink-prospects -> POST /seo/backlink-prospects', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'backlinkProspects'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/backlink-prospects');
  });

  it('smartlyq seo referring-domains -> POST /seo/referring-domains', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'referringDomains'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/referring-domains');
  });

  it('smartlyq seo backlink-anchors -> POST /seo/backlink-anchors', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'backlinkAnchors'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/backlink-anchors');
  });

  it('smartlyq seo spam-score -> POST /seo/spam-score', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'spamScore'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/spam-score');
  });

  it('smartlyq seo rank-history -> POST /seo/rank-history', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'rankHistory'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/rank-history');
  });

  it('smartlyq seo site-audit -> POST /seo/site-audit', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'siteAudit'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/site-audit');
  });

  it('smartlyq seo brand-lookup -> POST /seo/brand-lookup', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'brandLookup'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/brand-lookup');
  });

  it('smartlyq seo prompt-explorer -> POST /seo/prompt-explorer', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'promptExplorer'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/prompt-explorer');
  });

  it('smartlyq seo ai-audit -> POST /seo/ai-audit', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('seo', 'aiAudit'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/seo/ai-audit');
  });
});

describe('shorts', () => {
  it('smartlyq shorts generate -> POST /shorts/generate', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('shorts', 'generate'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/shorts/generate');
  });

  it('smartlyq shorts list -> GET /shorts', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('shorts', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/shorts');
  });

  it('smartlyq shorts get -> GET /shorts/{uid}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('shorts', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/shorts/test-id');
  });
});

describe('social', () => {
  it('smartlyq social list-accounts -> GET /social/accounts', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'listAccounts'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts');
  });

  it('smartlyq social list-posts -> GET /social/posts', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'listPosts'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/posts');
  });

  it('smartlyq social create-post -> POST /social/posts', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'createPost'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts');
  });

  it('smartlyq social schedule-post -> POST /social/posts/schedule', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'schedulePost'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/schedule');
  });

  it('smartlyq social get-post -> GET /social/posts/{post_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'getPost'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/posts/test-id');
  });

  it('smartlyq social update-post -> PATCH /social/posts/{post_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'updatePost'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('PATCH');
    expect(calls[0].path).toBe('/social/posts/test-id');
  });

  it('smartlyq social delete-post -> DELETE /social/posts/{post_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'deletePost'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/posts/test-id');
  });

  it('smartlyq social disconnect-account -> DELETE /social/accounts/{account_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'disconnectAccount'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/social/accounts/test-id');
  });

  it('smartlyq social get-account-health -> GET /social/accounts/{account_id}/health', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'getAccountHealth'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/health');
  });

  it('smartlyq social get-account-reconnect-url -> GET /social/accounts/{account_id}/reconnect-url', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'getAccountReconnectUrl'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/accounts/test-id/reconnect-url');
  });

  it('smartlyq social pause-account -> POST /social/accounts/{account_id}/pause', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'pauseAccount'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/accounts/test-id/pause');
  });

  it('smartlyq social resume-account -> POST /social/accounts/{account_id}/resume', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'resumeAccount'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/accounts/test-id/resume');
  });

  it('smartlyq social retry-post -> POST /social/posts/{post_id}/retry', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'retryPost'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/posts/test-id/retry');
  });

  it('smartlyq social connect-account-status -> GET /social/connect/{platform}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'connectAccountStatus'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/social/connect/test-id');
  });

  it('smartlyq social connect-account -> POST /social/connect/{platform}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('social', 'connectAccount'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/social/connect/test-id');
  });
});

describe('urls', () => {
  it('smartlyq urls shorten -> POST /urls/shorten', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('urls', 'shorten'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/urls/shorten');
  });

  it('smartlyq urls list -> GET /urls', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('urls', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/urls');
  });

  it('smartlyq urls get -> GET /urls/{url_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('urls', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/urls/test-id');
  });

  it('smartlyq urls delete -> DELETE /urls/{url_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('urls', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/urls/test-id');
  });

  it('smartlyq urls get-stats -> GET /urls/{url_id}/stats', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('urls', 'getStats'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/urls/test-id/stats');
  });
});

describe('videos', () => {
  it('smartlyq videos list-models -> GET /videos/models', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('videos', 'listModels'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/videos/models');
  });

  it('smartlyq videos generate -> POST /videos/generate', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('videos', 'generate'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/generate');
  });

  it('smartlyq videos list -> GET /videos', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('videos', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/videos');
  });

  it('smartlyq videos get -> GET /videos/{video_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('videos', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/videos/test-id');
  });

  it('smartlyq videos delete -> DELETE /videos/{video_id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('videos', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/videos/test-id');
  });

  it('smartlyq videos generate-hook -> POST /videos/hook', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('videos', 'generateHook'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/hook');
  });

  it('smartlyq videos suggest-broll -> POST /videos/broll-suggest', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('videos', 'suggestBroll'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/broll-suggest');
  });

  it('smartlyq videos suggest-emphasis -> POST /videos/emphasis', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('videos', 'suggestEmphasis'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/emphasis');
  });

  it('smartlyq videos generate-viral-thumbnail -> POST /videos/viral-thumbnail', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('videos', 'generateViralThumbnail'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/videos/viral-thumbnail');
  });
});

describe('webhooks', () => {
  it('smartlyq webhooks list -> GET /webhooks', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('webhooks', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/webhooks');
  });

  it('smartlyq webhooks create -> POST /webhooks', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('webhooks', 'create'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/webhooks');
  });

  it('smartlyq webhooks delete -> DELETE /webhooks/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('webhooks', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/webhooks/test-id');
  });
});

describe('workspaces', () => {
  it('smartlyq workspaces list -> GET /workspaces', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'list'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/workspaces');
  });

  it('smartlyq workspaces create -> POST /workspaces', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'create'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces');
  });

  it('smartlyq workspaces bulk-action -> POST /workspaces/bulk', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'bulkAction'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces/bulk');
  });

  it('smartlyq workspaces get -> GET /workspaces/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'get'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/workspaces/test-id');
  });

  it('smartlyq workspaces delete -> DELETE /workspaces/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'delete'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('DELETE');
    expect(calls[0].path).toBe('/workspaces/test-id');
  });

  it('smartlyq workspaces disable-saas -> POST /workspaces/{id}/disable-saas', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'disableSaas'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces/test-id/disable-saas');
  });

  it('smartlyq workspaces pause -> POST /workspaces/{id}/pause', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'pause'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces/test-id/pause');
  });

  it('smartlyq workspaces resume -> POST /workspaces/{id}/resume', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'resume'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('POST');
    expect(calls[0].path).toBe('/workspaces/test-id/resume');
  });

  it('smartlyq workspaces get-subscription -> GET /workspaces/{id}/subscription', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'getSubscription'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/workspaces/test-id/subscription');
  });

  it('smartlyq workspaces get-wallet -> GET /workspaces/{id}/wallet', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'getWallet'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/workspaces/test-id/wallet');
  });

  it('smartlyq workspaces list-saas-plans -> GET /saas/plans', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'listSaasPlans'), [], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/saas/plans');
  });

  it('smartlyq workspaces get-saas-plan -> GET /saas/plans/{id}', async () => {
    const { fetchImpl, calls } = mockFetch();
    await dispatch(cmd('workspaces', 'getSaasPlan'), ['test-id'], { apiKey: 'sqk_test_xxxxxxxxxxxx' }, { fetch: fetchImpl, maxRetries: 0 });
    expect(calls[0].method).toBe('GET');
    expect(calls[0].path).toBe('/saas/plans/test-id');
  });
});
