/**
 * Generates `src/commands.gen.ts` - the flat list of CLI command descriptors -
 * from `openapi.json`, using the same naming rules as the Node.js SDK so the
 * CLI surface mirrors the SDK surface exactly.
 */
import { writeFileSync } from 'node:fs';
import { kebabCase } from '../src/util';
import { buildModel } from './model';

const resources = buildModel();
const entries: string[] = [];

for (const r of resources) {
  for (const m of r.methods) {
    entries.push(
      '  ' +
        JSON.stringify({
          resourceKey: r.key,
          methodName: m.name,
          kebabMethod: kebabCase(m.name),
          pathParams: m.pathParams.map((p) => p.arg),
          hasBody: m.hasBody,
          bodyRequired: m.hasBody && m.bodyRequired,
          hasQuery: m.hasQuery,
          summary: m.summary,
          httpMethod: m.httpMethod,
          path: m.path,
        }) +
        ',',
    );
  }
}

const output = [
  '// This file is auto-generated by scripts/generate-commands.ts. Do not edit by hand.',
  '',
  '/** One CLI command: `smartlyq <resource> <kebabMethod> [pathArgs...]` -> SDK `sq[resourceKey][methodName](...)`. */',
  'export interface CommandDescriptor {',
  '  resourceKey: string;',
  '  methodName: string;',
  '  kebabMethod: string;',
  '  /** camelCase path parameter names, in call order. */',
  '  pathParams: string[];',
  '  hasBody: boolean;',
  '  bodyRequired: boolean;',
  '  hasQuery: boolean;',
  '  summary: string;',
  '  httpMethod: string;',
  '  path: string;',
  '}',
  '',
  'export const commands: CommandDescriptor[] = [',
  entries.join('\n'),
  '];',
  '',
].join('\n');

writeFileSync('src/commands.gen.ts', output);
console.log(`Generated src/commands.gen.ts: ${resources.length} resources, ${entries.length} commands.`);
