/**
 * Generates `tests/commands.gen.test.ts`: one test per CLI command, running the
 * CLI dispatch against a mocked SDK fetch and asserting the HTTP method + path.
 * Proves the CLI surface stays in lockstep with openapi.json and the SDK.
 */
import { writeFileSync } from 'node:fs';
import { kebabCase } from '../src/util';
import { buildModel, type MethodSpec } from './model';

function emitTest(resourceKey: string, m: MethodSpec): string {
  const expectedPath = m.path.replace(/\{[^}]+\}/g, 'test-id');
  const pathArgs = m.pathParams.map(() => `'test-id'`).join(', ');
  const flags = m.hasBody
    ? `{ apiKey: 'sqk_test_xxxxxxxxxxxx', data: '{}' }`
    : `{ apiKey: 'sqk_test_xxxxxxxxxxxx' }`;
  const cliName = `${kebabCase(resourceKey)} ${kebabCase(m.name)}`;

  return [
    `  it('smartlyq ${cliName} -> ${m.httpMethod} ${m.path}', async () => {`,
    `    const { fetchImpl, calls } = mockFetch();`,
    `    await dispatch(cmd('${resourceKey}', '${m.name}'), [${pathArgs}], ${flags}, { fetch: fetchImpl, maxRetries: 0 });`,
    `    expect(calls[0].method).toBe('${m.httpMethod}');`,
    `    expect(calls[0].path).toBe('${expectedPath}');`,
    `  });`,
  ].join('\n');
}

const resources = buildModel();
const blocks: string[] = [];

for (const r of resources) {
  blocks.push(
    [
      `describe('${kebabCase(r.key)}', () => {`,
      r.methods.map((m) => emitTest(r.key, m)).join('\n\n'),
      `});`,
    ].join('\n'),
  );
}

const output = [
  '// This file is auto-generated by scripts/generate-tests.ts. Do not edit by hand.',
  "import { describe, it, expect } from 'vitest';",
  "import { dispatch } from '../src/index';",
  "import { commands, type CommandDescriptor } from '../src/commands.gen';",
  '',
  'function cmd(resourceKey: string, methodName: string): CommandDescriptor {',
  '  const found = commands.find((c) => c.resourceKey === resourceKey && c.methodName === methodName);',
  '  if (!found) throw new Error(`No descriptor for ${resourceKey}.${methodName}`);',
  '  return found;',
  '}',
  '',
  'function mockFetch() {',
  '  const calls: { method: string; path: string }[] = [];',
  '  const fetchImpl: typeof fetch = async (input, init) => {',
  '    const url = new URL(String(input));',
  "    calls.push({ method: init?.method ?? 'GET', path: url.pathname.replace(/^\\/v1/, '') });",
  "    return new Response(JSON.stringify({ success: true, data: {} }), {",
  '      status: 200,',
  "      headers: { 'Content-Type': 'application/json' },",
  '    });',
  '  };',
  '  return { fetchImpl, calls };',
  '}',
  '',
  blocks.join('\n\n'),
  '',
].join('\n');

writeFileSync('tests/commands.gen.test.ts', output);
const count = resources.reduce((n, r) => n + r.methods.length, 0);
console.log(`Generated tests/commands.gen.test.ts: ${count} command tests.`);
